import { Type } from '@nestjs/common';

import { OptionalIds } from '../../types/optional-ids.type';
import { DeepEntityPartial } from './deep-entity-partial.type';

// A repository input is almost complete : it contains trackable fields
// but still has optional _ids. If so, they wiil be generated by mongodb

export type SimpleRepositoryInputObj<E extends object> = OptionalIds<E>;

export type PartialSimpleRepositoryInputObj<E extends object> =
  DeepEntityPartial<SimpleRepositoryInputObj<E>>;

export type SimpleRepositoryInput<E extends object> = Type<
  SimpleRepositoryInputObj<E>
>;

export type PartialSimpleRepositoryInput<E extends object> = Type<
  PartialSimpleRepositoryInputObj<E>
>;
